WebBasedMITS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBasedMITS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebBasedMITS/Controllers/JunctionListController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WeBBasedMITSData;

namespace WebBasedMITS.Controllers
{
    public class JunctionListController : Controller
    {
        // GET: JunctionList
        private IRepository<JunctionList> repository = null;
        JunctionListRepository junctionlistRepository = new JunctionListRepository();
        public ActionResult Index()
        {
            return View();
        }
        public JunctionListController()
        {
            this.repository = new GenericRepository<JunctionList>();
        }
        public JunctionListController(GenericRepository<JunctionList> repository)
        {
            this.repository = repository;
        }

        public async Task<ActionResult> GetJunctionList()
        {
            List<JunctionList> junctionsList1;
            junctionsList1 = await junctionlistRepository.GetJunctionLists().ToListAsync();
            return View(junctionsList1);
        }
        public ActionResult Create()//this is used to call create form to enter fields after user click on the create button the bottom Create is called
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(JunctionList junction)//this is called when user clicked on create save button in the form
        {
            if (ModelState.IsValid)
            {
                repository.Insert(junction);
                repository.Save();
                return RedirectToAction("GetJunctionList");
            }
            return View(junction);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var employee = junctionlistRepository.mITSDatabaseEntities.JunctionLists.SingleOrDefault(e => e.Id == id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [HttpPost]
        public ActionResult Edit(JunctionList junction)
        {
            if (ModelState.IsValid)
            {

                repository.Update(junction);
                repository.Save();
                return RedirectToAction("GetJunctionList");
            }

            return View(junction);
        }
        public ActionResult DetailsByID(int Id)
        {


            var junction = repository.GetById(Id);

            if (junction == null)
            {
                return HttpNotFound();
            }
            return View(junction);
        }
        public ActionResult Delete(int? Id)//this is used to call delete form to enter fields after user click on the delete button the bottom delete is called
        {
            var junction = junctionlistRepository.mITSDatabaseEntities.JunctionLists.SingleOrDefault(e => e.Id == Id);

            if (junction == null)
            {
                return HttpNotFound();
            }
            return View(junction);
        }

        [HttpPost]//the following is called when submit is used in the post form in cshtml
        public ActionResult Delete(int Id)//this is called when user clicked on delete button in the form
        {
            repository.Delete(Id);
            repository.Save();
            return RedirectToAction("GetJunctionList");
        }
    }
}

WebBasedMITS/Controllers/JunctionSpecificationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WeBBasedMITSData;

namespace WebBasedMITS.Controllers
{
    public class JunctionSpecificationController : Controller
    {
        // GET: JunctionSpecification
        private IRepository<JunctionList> repository = null;
        JunctionListRepository junctionlistRepository = new JunctionListRepository();
        public ActionResult Index()
        {
            return View();
        }
        public async Task<ActionResult> JunctionListSpecification()
        {
            List<JunctionList> junctionsList1;
            junctionsList1 = await junctionlistRepository.GetJunctionLists().ToListAsync();
            return View(junctionsList1);
        }
    }
}

WebBasedMITS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebBasedMITS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebBasedMITS/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Dashboard";
}
@using (Html.BeginForm())
{
	<div class="container-fluid">
		<div class="row mt-3">

			<div class="col-12 col-lg-6 col-xl-3">
				<a href="/JunctionList/GetJunctionList">
					<div class="card" style="background-color:rgba(108, 117, 125, 0.5)">
						<div class="card-body">
							<div class="media align-items-center">
								<div class="w-icon"><i class="fa fa-bars text-white" style="font-size:xx-large"></i></div>
								<div class="media-body ml-3 border-left-xs border-light-3">
									<h4 class="mb-1 ml-3" style="color:azure; font-family:Arial, Helvetica, sans-serif">Manage Junction</h4>

								</div>
							</div>
						</div>
					</div>
				</a>
			</div>

			<div class="col-12 col-lg-6 col-xl-3">
				<a href="/Home/JunctionMonitoring">
					<div class="card" style="background-color:rgba(108, 117, 125, 0.5)">
						<div class="card-body">
							<div class="media align-items-center">
								<div class="w-icon"><i class="fa fa-laptop text-white" style="font-size:xx-large"></i></div>
								<div class="media-body ml-3 border-left-xs border-light-3">
									<h4 class="mb-1 ml-3" style="color:azure; font-family:Arial, Helvetica, sans-serif">Junction Monitoring</h4>
								</div>
							</div>
						</div>
					</div>
				</a>
			</div>
			<div class="col-12 col-lg-6 col-xl-3">
				<a href="/Home/JunctionMonitoring">
					<div class="card" style="background-color:rgba(108, 117, 125, 0.5)">
						<div class="card-body">
							<div class="media align-items-center">
								<div class="w-icon"><i class="fa fa-clock-o text-white" style="font-size:xx-large"></i></div>
								<div class="media-body ml-3 border-left-xs border-light-3">
									<h4 class="mb-1 ml-3" style="color:azure; font-family:Arial, Helvetica, sans-serif">Junction VA Time Settings</h4>
								</div>
							</div>
						</div>
					</div>
				</a>
			</div>
			<div class="col-12 col-lg-6 col-xl-3">
				<a href="/JunctionSpecification/JunctionListSpecification">
					<div class="card" style="background-color:rgba(108, 117, 125, 0.5)">
						<div class="card-body">
							<div class="media align-items-center">
								<div class="w-icon"><i class="fa fa-laptop text-white" style="font-size:xx-large"></i></div>
								<div class="media-body ml-3 border-left-xs border-light-3">
									<h4 class="mb-1 ml-3" style="color:azure; font-family:Arial, Helvetica, sans-serif">Junction Specification</h4>
								</div>
							</div>
						</div>
					</div>
				</a>
			</div>
		</div>
	</div>
}

WebBasedMITS/Views/JunctionList/Create.cshtml
@model WeBBasedMITSData.JunctionList

@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
	<div class="form-horizontal">
		<h4>Employee</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.JunctionId)

		<div class="form-row ">
			<div class="col-md-4">
				@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
				<div>
					@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
				</div>
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				@Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
				<div>
					@Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="form-row">
			<div class="col-md-4">
				@Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
				<div>
					@Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
				</div>
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				@Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
				<div>
					@Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="form-row">
			<div class="col-md-10">
				@Html.LabelFor(model => model.JunctionIp, htmlAttributes: new { @class = "control-label col-md-2" })
				<div>
					@Html.EditorFor(model => model.JunctionIp, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.JunctionIp, "", new { @class = "text-danger" })
				</div>
			</div>

		</div>
		@*<div class="form-group">
				@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
				</div>
			</div>*@
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "GetJunctionList")
</div>

WebBasedMITS/Views/JunctionList/Delete.cshtml
@model WeBBasedMITSData.JunctionList

@{
	ViewBag.Title = "Delete";
}

<h2 style="color:#f8b739">Delete</h2>

<div>
	<h4>Employee</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Id)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.JunctionId)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.JunctionIp)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.District)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.JunctionFeatureId)
		</dt>

	</dl>

	@using (Html.BeginForm())
	{

		<div class="form-actions no-color">
			<input type="submit" value="Delete" class="btn btn-default" /> |
			@Html.ActionLink("Back to List", "GetJunctionList")
		</div>
	}
</div>

WebBasedMITS/Views/JunctionList/DetailsByID.cshtml
@model WeBBasedMITSData.JunctionList
@{
	ViewBag.Title = "DetailsByID";
}
@{
	var latitude = (decimal)22.9019;
	var longitude = (decimal)64.5176;
	var zoomLevel = 9;

	var junctionFeaturesName = string.Empty;
	if (Model.Latitude != null)
	{
		latitude = Model.Latitude.Value;
		zoomLevel = 16;
	}

	if (Model.Longitude != null)
	{
		longitude = Model.Longitude.Value;
	}
}

@using (Html.BeginForm())
{
	<form>
		<h4 style="color:#f8b739">Junction detail</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "" })
		@Html.HiddenFor(model => model.Id)
		<div class="form-row">
			<div class="form-group col-md-10">
				@Html.LabelFor(model => model.JunctionId@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.JunctionId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@Html.ValidationMessageFor(model => model.JunctionId, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-row ">
			<div class="col-md-4">
				@Html.LabelFor(model => model.Name@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				@Html.LabelFor(model => model.District@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)

				@Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-row">
			<div class="col-md-4">
				@Html.LabelFor(model => model.Latitude@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				@Html.LabelFor(model => model.Longitude@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-row">
			<div class="col-md-10">
				@Html.LabelFor(model => model.JunctionIp@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.JunctionIp, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@Html.ValidationMessageFor(model => model.JunctionIp, "", new { @class = "text-danger" })
			</div>

		</div>
		<br />
		<div class="form-group">
			<label> Junction Location</label>
			<div class="row">

				<div class="col-md-12">
					<div id="googleMap" style="height: 500px"></div>
				</div>
			</div>
		</div>
		@*<div class="form-group">
				@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
				</div>
			</div>*@
		@*<div class="form-row">
				<div class="col-md-offset-2 col-md-2">
					<button type="submit" value="Save" class="btn btn-primary" />
				</div>
			</div>*@
	</form>
}
@Html.ActionLink("Back to List", "GetJunctionList")
@section scripts{
	<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyC4mC-WLZABobydAkWwVhyaYQerMssTTwQ"></script>
	<script src="~/Scripts/jquery-3.4.1.js"></script>
	<script type="text/javascript">
			$(document).ready(function () {

				window.onload = initialize;

				function initialize() {
					var map = new google.maps.Map(document.getElementById('googleMap'), {
						zoom: @zoomLevel,
						center: new google.maps.LatLng(@latitude, @longitude),
						mapTypeId: google.maps.MapTypeId.ROADMAP
					});

					var vMarker = new google.maps.Marker({
						position: new google.maps.LatLng(@latitude, @longitude),
						draggable: false
					});

					//google.maps.event.addListener(vMarker, 'dragend', function (evt) {
					//    $("#latitude").val(evt.latLng.lat().toFixed(6));
					//    $("#longitude").val(evt.latLng.lng().toFixed(6));

					//    map.panTo(evt.latLng);
					//});

					map.setCenter(vMarker.position);

					vMarker.setMap(map);
				}
			});

	</script>
}

WebBasedMITS/Views/JunctionList/Edit.cshtml
@model WeBBasedMITSData.JunctionList

@{
	ViewBag.Title = "Edit";
}

<h2 style="color:#f8b739">Edit</h2>

@using (Html.BeginForm())
{
	<form>
		<h4 style="color:#f8b739">Junction List</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "" })
		@Html.HiddenFor(model => model.Id)
		<div class="form-row">
			<div class="form-group col-md-10">
				@Html.LabelFor(model => model.JunctionId@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.JunctionId, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.JunctionId, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-row ">
			<div class="col-md-4">
				@Html.LabelFor(model => model.Name@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				@Html.LabelFor(model => model.District@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)

				@Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-row">
			<div class="col-md-4">
				@Html.LabelFor(model => model.Latitude@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				@Html.LabelFor(model => model.Longitude@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-row">
			<div class="col-md-10">
				@Html.LabelFor(model => model.JunctionIp@*, htmlAttributes: new { @class = "control-label col-md-2" }*@)
				@Html.EditorFor(model => model.JunctionIp, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.JunctionIp, "", new { @class = "text-danger" })
			</div>

		</div>
		<br />
		<div class="form-row">
			<div class="col-md-4">
				<input type="submit" value="Save" class="btn btn-primary" />

			</div>

		</div>
		@*<div class="form-group">
				@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
				</div>
			</div>*@
		@*<div class="form-row">
				<div class="col-md-offset-2 col-md-2">
					<button type="submit" value="Save" class="btn btn-primary" />
				</div>
			</div>*@
	</form>
}
@Html.ActionLink("Back to List", "GetJunctionList")

WebBasedMITS/Views/JunctionList/GetJunctionList.cshtml
@model IEnumerable<WeBBasedMITSData.JunctionList>

@{
	ViewBag.Title = "GetJunctionList";
}

<button class="btn btn-primary" onclick="location.href='@Url.Action("Create New", "Create")';return false;">+Add Junction</button>
<table class="table table-bordered table-responsive table-hover table-striped table-light">
	<tr>
		<th>Junction ID </th>
		<th>Junction Name </th>
		<th>District</th>
		<th>Latitude</th>
		<th>Longitude</th>
		<th></th>

	</tr>
	@foreach (var d in Model)
	{
<tr>
	<td>@d.JunctionId</td>
	<td>@d.Name</td>
	<td>@d.District</td>
	<td>@d.Latitude</td>
	<td>@d.Longitude</td>
	<td>
		@Html.ActionLink("Edit", "Edit", new { id = d.Id }) |
		@Html.ActionLink("Detail", "DetailsByID", new { id = d.Id }) |
		@Html.ActionLink("Delete", "Delete", new { id = d.Id })
	</td>
</tr>

	}
</table>

WebBasedMITS/Views/JunctionList/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

WebBasedMITS/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
	<title>MITS</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
	<link rel="stylesheet" href="~/Content/icons.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
	<link href="~/Content/table.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/Content/style.css">
	@RenderSection("scripts", required: false)
</head>
<body>

	<div class="wrapper d-flex align-items-stretch" style="background: url('../../images/Background3.jpg')no-repeat center center;fixed-webkit-background-size: cover;-moz-background-size: cover;-o-background-size:cover;background-size: cover;">
		<nav id="sidebar">
			<div class="p-4 pt-5">
				<a href="#" class="img logo rounded-circle mb-auto" style="background-image: url('../../images/logo.png');background-size:auto; "></a>
				<ul class="list-unstyled components mb-5">
					<li><a href="@Url.Action("Index", "Home")"><i class="fa fa-credit-card"></i> <span>Dashboard</span></a></li>
					<li><a href="@Url.Action("GetJunctionList", "JunctionList")"><i class="fa fa-list"></i> <span>Junction List</span></a></li>
					<li>@Html.ActionLink("About", "About", "Home")</li>
					<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
				</ul>

				<div class="footer">
					<p>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;
						<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
				</div>

			</div>
		</nav>

		<!-- Page Content  -->
		<div id="content" class="p-0 p-md-2">

			<nav class="navbar navbar-expand-lg navbar-light bg-dark navbar-fixed-top">
				<div class="container-fluid">

					<button type="button" id="sidebarCollapse" class="btn btn-primary">
						<i class="fa fa-bars"></i>
						<span class="sr-only">Toggle Menu</span>
					</button>
					<button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<i class="fa fa-bars"></i>
					</button>
					<h2 style="color:azure">Web Based Monitoring System</h2>

				</div>
			</nav>
			@RenderBody()
		</div>
	</div>

	<script src="~/Scripts/jquery.min.js"></script>
	<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
	<script src="~/Scripts/popper.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/main.js"></script>
	<script src="~/Scripts/table.js"></script>
</body>
</html>